### ISSUE TITLE
Not working in Tinkers Construct 1.10.2

### ISSUE THREAD

**Issue by DRTR0** [SilentChaos512/FunOres#12] opened 2016-07-19 17:22 UTC
Your mod is not working with Tinkers Construct in 1.10.2. Tinkers supports ore gen from other mods, but I don't see tin, copper, aluminum, etc. being enabled in the mod. I should have tested first. Had a few stacks of tin and copper to make bronze and realized I couldn't do anything with it. :/

**Comment by SilentChaos512** [comment] 2016-07-19 18:57
Why am I not surprised... My ores are in the ore dictionary, so they _should_ work. Although I rarely use TCon, so there may be something I'm missing. If it's something I can fix, it will be fixed by sometime tomorrow, probably.

**Comment by jriwanek** [comment] 2016-07-19 20:35
Take a look at the code in modernmetals, specifically the Tinkers Plugin code, most of the common metals _should_ just register, but there's a few Tinkers doesn't know about so you have to make a fluid and send an IMC for them at minimum, I also register a fluid block too but that's so it can be used without tinkers.

If you need a hand, just let me know.

**Comment by SilentChaos512** [comment] 2016-07-19 22:29
Thanks for the tip!

I can confirm that all metal ores (even copper and tin) are not working in the TCon smeltery in both 1.9.4 and 1.10.2. Except that copper seems to work in 1.10.2... Strange. I'll give registering the fluids a shot.

**Comment by jriwanek** [comment] 2016-07-19 22:39
Might be worth looking into simplifying your code, copper _should_ work in all versions of tinkers as Tcon already provides the fluid, same with tin, brass, nickel, zinc & others:

https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/TinkerIntegration.java

**Comment by SilentChaos512** [comment] 2016-07-19 23:36
Moving oredict registration to preInit seems to fix everything except platinum, aluminium (because of the spelling, I assume), and titanium. So I'll just need to add fluids for those three, correct?

**Comment by jriwanek** [comment] 2016-07-20 00:17
Sounds about right, aye.

**Comment by DRTR0** [comment] 2016-07-20 02:56
Didn't expect such a fast response. Like 90% of modders don't even seem to read these. Thanks. :)

**Comment by SilentChaos512** [comment] 2016-07-20 03:06
I try, at least :). Tonight I'll release a new build of Silent Lib that will fix most of the ores. I'll try to get the other three (platinum, aluminium, titanium) fixed tomorrow or the next day. I've never done fluids before, so... hopefully I don't make too big of a mess of the code.

**Comment by DRTR0** [comment] 2016-07-20 05:11
Thank you, it works now. :)

Also a suggestion (if you want me to make another post I can) is to add in the config if you want the plates, gears, etc. enabled or disabled. I don't really use them and don't feel like disabling them all with CraftTweaker before I host a server for friends/family. Just laziness. :p I guess I could just hide them in JEI.

**Comment by jriwanek** [comment] 2016-07-20 05:48
You mean like:

https://github.com/SilentChaos512/FunOres/issues/7

**Closed as completed** 2016-07-21 17:47 UTC
